GET http://localhost/api/get_thesis.php

###
POST http://localhost/api/get_detail.php
content-type: application/json

{
    "paper_id": "3604018"
}

###
POST http://localhost/api/set_history.php
content-type: application/json

{
    "geo_student_id": "",
    "geo_cmuitaccount": "sakda.homhuan@cmu.ac.th",
    "geo_firstname_TH": "ศักดิ์ดา",
    "geo_lastname_TH": "หอมหวล",
    "geo_organization_name_TH": "คณะสังคมศาสตร์",
    "paper_id": "3604003"
}

###
POST http://localhost/api/get_history.php
content-type: application/json

{
    "geo_cmuitaccount": "sakda.homhuan@cmu.ac.th"
}